print("Welcome to the mini Python demo!")
print("This program shows what print can do.")
print()
print("Line 1: Hello, World!")
print("Line 2: Python is fun.")
print("Line 3: 1 + 1 =", 1 + 1)
print("Line 4: Stars: " + "*" * 10)
print("Line 5:")
print(" - Apples")
print(" - Bananas")
print(" - Cherries")
print()
print("Thanks for watching!")
